SELECT
    CASE
        WHEN COUNT(*) > 0 THEN
            'DATA QUALITY FAILED: Invalid latitude or longitude detected'
        ELSE
            'COORDINATE CHECK PASSED'
    END AS QUALITY_RESULT
FROM OPENSKY_DB.SILVER.OPENSKY_CLEAN
WHERE LATITUDE NOT BETWEEN -90 AND 90
   OR LONGITUDE NOT BETWEEN -180 AND 180;
