SELECT
    CASE
        WHEN COUNT(*) = 0 THEN
            'DATA QUALITY FAILED: SILVER table is empty'
        ELSE
            'SILVER CHECK PASSED'
    END AS QUALITY_RESULT
FROM OPENSKY_DB.SILVER.OPENSKY_CLEAN;
