SELECT
    CASE
        WHEN MIN(CNT) = 0 THEN
            'DATA QUALITY FAILED: GOLD tables contain no data'
        ELSE
            'GOLD CHECK PASSED'
    END AS QUALITY_RESULT
FROM (
    SELECT COUNT(*) AS CNT
    FROM OPENSKY_DB.GOLD.FLIGHTS_PER_COUNTRY_HOUR

    UNION ALL

    SELECT COUNT(*)
    FROM OPENSKY_DB.GOLD.AIRCRAFT_CATEGORY_STATS

    UNION ALL

    SELECT COUNT(*)
    FROM OPENSKY_DB.GOLD.BUSIEST_AIRSPACE_REGIONS
);
