CREATE OR REPLACE TABLE OPENSKY_DB.GOLD.AIRCRAFT_CATEGORY_STATS AS

SELECT
    CATEGORY,

    COUNT(DISTINCT ICAO24) AS AIRCRAFT_COUNT,

    ROUND(
        AVG(BARO_ALTITUDE),
        2
    ) AS AVG_ALTITUDE,

    ROUND(
        AVG(VELOCITY),
        2
    ) AS AVG_VELOCITY,

    ROUND(
        AVG(VERTICAL_RATE),
        2
    ) AS AVG_VERTICAL_RATE

FROM OPENSKY_DB.SILVER.OPENSKY_CLEAN

GROUP BY CATEGORY;
