CREATE OR REPLACE TABLE OPENSKY_DB.GOLD.AIRSPACE_ACTIVITY AS

SELECT
    FLOOR(LATITUDE / 5) * 5 AS LAT_GRID,
    FLOOR(LONGITUDE / 5) * 5 AS LON_GRID,

    COUNT(*) AS AIRCRAFT_OBSERVATIONS,

    COUNT(DISTINCT ICAO24) AS UNIQUE_AIRCRAFT,

    ROUND(
        AVG(BARO_ALTITUDE),
        2
    ) AS AVG_ALTITUDE,

    ROUND(
        AVG(VELOCITY),
        2
    ) AS AVG_VELOCITY

FROM OPENSKY_DB.SILVER.OPENSKY_CLEAN

WHERE LATITUDE IS NOT NULL
  AND LONGITUDE IS NOT NULL

GROUP BY
    FLOOR(LATITUDE / 5) * 5,
    FLOOR(LONGITUDE / 5) * 5;
