CREATE OR REPLACE TABLE OPENSKY_DB.GOLD.BUSIEST_AIRSPACE_REGIONS AS

SELECT

    CASE
        WHEN LATITUDE >= 0 AND LONGITUDE >= 0
            THEN 'Northeast'
        WHEN LATITUDE >= 0 AND LONGITUDE < 0
            THEN 'Northwest'
        WHEN LATITUDE < 0 AND LONGITUDE >= 0
            THEN 'Southeast'
        ELSE 'Southwest'
    END AS AIRSPACE_REGION,

    COUNT(DISTINCT ICAO24) AS AIRCRAFT_COUNT,

    ROUND(
        AVG(BARO_ALTITUDE),
        2
    ) AS AVG_ALTITUDE,

    ROUND(
        AVG(VELOCITY),
        2
    ) AS AVG_VELOCITY

FROM OPENSKY_DB.SILVER.OPENSKY_CLEAN

WHERE LATITUDE IS NOT NULL
  AND LONGITUDE IS NOT NULL

GROUP BY
    AIRSPACE_REGION;
