CREATE OR REPLACE TABLE OPENSKY_DB.GOLD.FLIGHTS_PER_COUNTRY_HOUR AS

SELECT
    ORIGIN_COUNTRY,
    DATE_TRUNC(
        'HOUR',
        INGESTION_TIMESTAMP
    ) AS FLIGHT_HOUR,

    COUNT(*) AS FLIGHT_COUNT

FROM OPENSKY_DB.SILVER.OPENSKY_CLEAN

WHERE ORIGIN_COUNTRY IS NOT NULL
  AND TRIM(ORIGIN_COUNTRY) <> ''
  AND INGESTION_TIMESTAMP IS NOT NULL

GROUP BY
    ORIGIN_COUNTRY,
    DATE_TRUNC('HOUR', INGESTION_TIMESTAMP);
