COPY INTO OPENSKY_DB.RAW.OPENSKY_RAW
FROM @OPENSKY_S3_STAGE
PATTERN = '.*year=[0-9]{4}/month=[0-9]{2}/day=[0-9]{2}/hour=[0-9]{2}/.*\.csv'
FILE_FORMAT = (
    FORMAT_NAME = OPENSKY_CSV_FORMAT
)
ON_ERROR = 'CONTINUE';
